name: ukhsc_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: 3.27.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.6.3
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  ua_client_hints:
    # TODO: iOS app name workaround: https://github.com/SiongSng/flutter_ua_client_hints/commit/2011d084d2f419725d59f9d994e66904c1b48f18
    git:
      url: https://github.com/SiongSng/flutter_ua_client_hints.git
      ref: main
      sha: 2011d084d2f419725d59f9d994e66904c1b48f18
  url_launcher: ^6.3.1
  envied: ^1.1.0
  flutter_secure_storage: ^10.0.0-beta.4
  dart_jsonwebtoken: ^2.16.0
  logging: ^1.3.0
  logging_appenders: ^1.3.1
  sentry_flutter: ^8.12.0
  sentry_dio: ^8.12.0
  sentry_logging: ^8.12.0
  sentry_dart_plugin: ^2.4.0
  connectivity_plus: ^6.1.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4
  flutter_gen_runner: ^5.8.0
  go_router_builder: ^2.7.3
  freezed: ^2.5.8
  freezed_lint: ^0.0.7
  json_serializable: ^6.9.3
  envied_generator: ^1.1.0

dependency_overrides:
  # TODO: Flutter Gen Workaround (dart_style)
  # https://github.com/FlutterGen/flutter_gen/pull/615
  # https://github.com/FlutterGen/flutter_gen/issues/625
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      sha: 57ca3a47085977b6c0f07a66661fb769f030aeb6
      path: packages/core/

flutter:
  uses-material-design: true
  fonts:
    - family: Dela Gothic One
      fonts:
        - asset: assets/fonts/Dela_Gothic_One/DelaGothicOne-Regular.ttf
    - family: Noto Sans TC
      fonts:
        - asset: assets/fonts/Noto_Sans_TC/NotoSansTC-VariableFont_wght.ttf
          weight: 700
  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true

sentry:
  upload_source_maps: true
  upload_sources: true
