source "https://rubygems.org"

gem "fastlane",  :git => "https://github.com/fastlane/fastlane.git", :branch => 'master', :ref => 'b626fb18597eee88de0e08beba77070e2fecc299'
gem 'abbrev'
gem 'logger'
gem 'mutex_m'
gem 'csv'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
