# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

FileNotFound = Class.new(StandardError)

def fetch_version
  path = "../local.properties"

  if File.exist?(path)
    content = File.read(path)

    buildRegex = /(?<=flutter.versionCode=).+/

    build = buildRegex.match(content)[0]
    build
  else
    raise FileNotFound
  end
end

def populate_changelog
  metadata_dir = "./metadata/android/zh-TW/changelogs"

  version = fetch_version
  changelog = read_changelog(changelog_path: '../../CHANGELOG.md')

  destination = "#{metadata_dir}/#{version}.txt"

  File.open(destination, 'w') do |f|
    f << changelog
  end
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new beta build to Google Play"
  lane :beta do
    sh "flutter build appbundle"
    populate_changelog
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play_store_config.json',
      )
  end

  desc "Promote beta track to production"
  lane :promote_to_production do
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      skip_upload_changelogs: true,
      json_key: 'play_store_config.json',
      )
  end

  desc "Submit a new production build to Google Play"
  lane :production do
    sh "flutter build appbundle"
    populate_changelog
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key: 'play_store_config.json',
      )
  end
end